provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  signed-and-sealed:
    lang: go
    handler: ./signed-and-sealed
    image: signed-and-sealed:0.1
    environment:
      hmac_secret: "richard_gee"

  python-world:
    lang: python3
    handler: ./python-world
    image: alexellis2/python-world:0.4
#    secrets:
#     - secret


